server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${fxz.datasource.driver-class-name}
      url: jdbc:mysql://${fxz.datasource.host}:${fxz.datasource.port}/${fxz.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${fxz.datasource.username}
      password: ${fxz.datasource.password}
  redis:
    host: ${fxz.redis.host}
    port: ${fxz.redis.port}
    password: ${fxz.redis.password}
    database: ${fxz.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fxz.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      fxz:
        mapper: debug
        service: info
        controller: info

fxz:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: fxzfxz
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: fxzuser
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${fxz.alioss.endpoint}
    access-key-id: ${fxz.alioss.access-key-id}
    access-key-secret: ${fxz.alioss.access-key-secret}
    bucket-name: ${fxz.alioss.bucket-name}
  wechat:
    appid: ${fxz.wechat.appid}
    secret: ${fxz.wechat.secret}
